### ISSUE TITLE
-	Create a task to combine and minify user javascript files into a ‘script.js’ and put into build dir 

### ISSUE THREAD

**Issue by bradley-stone** [hdavtian/gulp#3]
I think we can just add this to the "scripts" task.

**Comment by hdavtian** [comment]
Ok, I will take this :)

**Comment by hdavtian** [comment]
I have added two tasks: 'scripts-site' and 'scripts-vendor'. Each will concatenate, minify and copy js files to build folder. I have also added documentation to the index.html page about how this works
