### ISSUE TITLE
Create task for image optimization

### ISSUE THREAD

**Issue by bradley-stone** [hdavtian/gulp#4]

**Comment by hdavtian** [comment]
hey @bradley-stone , please implement image optimization to your image task. I was working with gulp-imagemin earlier and it looked good. https://www.npmjs.com/package/gulp-imagemin

**Comment by bradley-stone** [comment]
Image minification has been implemented. 

Commit 8fa35914657b0077a1fd4138ce9a99980376ac1c

**Comment by hdavtian** [comment]
:+1:
